### ISSUE TITLE
JOSS Paper - more clearly state what deficiencies with multiple testing

### ISSUE THREAD

**Issue by gavinsimpson** [wilsoncai1992/data.adapt.multi.test#13]
The paper currently alludes to problems with existing multiple testing methods, particularly in high dimensional settings, but fails to explain, even briefly, what these deficiencies are.

Please state more clearly what the problems are that **data.adapt.multi.test** solves, not just that there are problems.

This is needed to address the **Statement of Need** sections of the JOSS review.

openjournals/joss-reviews#161

**Comment by wilsoncai1992** [comment]
The issue is completed by commit 840ace169b351976d4e5d3435ef98a345c4e2116
